### ISSUE TITLE
Donations 

### ISSUE THREAD

**Issue by pointbiz** [spsina/bip47#1]
Hi, I would like to donate 0.1 BTC split between the two developers of this library. 

Can we dogfood and use BIP47 addresses that are Samourai wallet compatible? 

Please each post your BIP47 address if you accept this donation offer.

**Comment by alimahdiyar** [comment]
Thanks. We appreciate that :)
The library is ready to use and we also published the package on npm so it's easier to use.
https://www.npmjs.com/package/@spsina/bip47

I added the donation address to the readme :)

**Comment by spsina** [comment]
Very generous of you, thanks!

**Comment by pointbiz** [comment]
Thanks sent.
